apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.15.0 (e3cd4d4)
  creationTimestamp: null
  labels:
    io.kompose.service: game-changers-client
  name: game-changers-client
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: game-changers-client
    spec:
      containers:
      - image: game-changers-client
        name: game_changers_client
        ports:
        - containerPort: 4200
        resources: {}
        volumeMounts:
        - mountPath: /usr/src/app
          name: game-changers-client-claim0
      restartPolicy: Always
      volumes:
      - name: game-changers-client-claim0
        persistentVolumeClaim:
          claimName: game-changers-client-claim0
status: {}
